解决 zip 文件未被关闭的问题及部分编译警告
mysterywolf/minizip pull request #2
Opened 2022-03-17 09:45 UTC by a1012112796

- 经核查源代码，unzCloseCurrentFile 只释放了内存, 并未调用
关闭文件的接口, unzClose 可以正常关闭文件，故全部改用 unzClose.
ref:
https://github.com/mysterywolf/minizip/blob/7ec06eeb2dcf7bad661bcfe4ddfde4bb929c4aa8/unzip.c#L511-L525

- 解决几处比较明显的编译警告

Signed-off-by: a1012112796 <1012112796@qq.com>

fix #1

2022-03-17 23:16 UTC, mysterywolf requested changes
谢谢提交pr，有两处问题需要改一下

2022-03-17 23:16 UTC, mysterywolf commented on miniunz.c
> +#include "dfs_posix.h"
这个头文件已经在4.1.0版本之后移除掉了 不要添加这个头文件

2022-03-17 23:16 UTC, mysterywolf commented on zip.c
> -
这个请不要删除，用//注释掉吧

2022-03-18 00:04 UTC, a1012112796 commented on miniunz.c
> +#include "dfs_posix.h"
后面用到了 `chdir()`, 请问改用哪个头文件?

2022-03-18 00:09 UTC, mysterywolf commented on miniunz.c
> +#include "dfs_posix.h"
#include <unistd.h> 在linux下怎么用 rt-thread就怎么用 头文件这块就符合类unix了

2022-03-19 17:48 UTC, merged

2022-03-19 17:48 UTC, mysterywolf commented
谢谢 已经手动帮你修改并合并

2022-03-19 17:48 UTC, mysterywolf commented
感谢贡献PR！

2022-03-20 01:57 UTC, a1012112796 commented on miniunz.c
> +#include "dfs_posix.h"
https://github.com/mysterywolf/minizip/blob/9cbdcf39d4c2692ccd381a2385802194f715584d/miniunz.c?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L16-L19

另外提一下，其实 unistd.h 已经写了,只是限制在了 unix 下使用，如果看不惯这个警告可以放开这个限制例如
```DIFF
diff --git a/miniunz.c b/miniunz.c
index becd111..d28ecf7 100644
--- a/miniunz.c
+++ b/miniunz.c
@@ -13,7 +13,7 @@
 #include <errno.h>
 #include <fcntl.h>

-#ifdef unix
+#if defined(unix) || defined(__RTTHREAD__)
 # include <unistd.h>
 # include <utime.h>
 #endif
```